log:
  level: DEBUG

# accessLog: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
    watch: true
  file:
    directory: /config
    watch: true

entryPoints:
  "traefik": # traefik dashboard
    address: ":8080"
  "whoami": # http
    address: ":8081"

api:
  dashboard: true

experimental:
  localPlugins:
    traefik_tianji_plugin:
      moduleName: "github.com/msgbyte/tianji/apps/traefik-tianji-plugin"
